%==========================================================================
% Source codes:  beltopkit -- A topology-based toolkit for generalized nanobelts
% Author:        Yang Wang (yangwang@yzu.edu.cn)
% ORCID:         https://orcid.org/0000-0003-2540-2199
% Last Modified: March 18, 2026
% License:       For academic and non-commercial use only.
%                Copyright (c) 2026 Yang Wang. All rights reserved.
%==========================================================================

% Generated by ChatGPT:
%
% To determine the periodic symmetry of an array in MATLAB, 
% considering circular symmetry, we need to find the smallest 
% repeating sub-array or "periodic unit" that repeats to form 
% the entire array. Here's an algorithm that can help you 
% identify the periodic unit:
%
% Steps:
%
% Get the array length: Identify the length of the array.
% Loop over possible period lengths: Try different potential 
% period lengths starting from 1 and check if the array can be 
% built by repeating the sub-array of that length.
% Check for symmetry: For each potential period, check if 
% repeating the sub-array forms the entire original array.
% Return the periodic unit: Once a valid period is found, 
% return the corresponding sub-array.

function [periodic_unit, num_repeats] = find_periodic_unit(A)
    n = length(A);  % Get the length of the array
    periodic_unit = [];  % Initialize the periodic unit
    num_repeats = 0;  % Initialize the number of repeating units

    % Loop over possible period lengths
    for p = 1:n
        if mod(n, p) == 0  % Check if n is divisible by p (potential period length)
            candidate_unit = A(1:p);  % Extract candidate sub-array of length p
            % Replicate the candidate sub-array and compare to the original array
            if isequal(repmat(candidate_unit, 1, n/p), A)
                periodic_unit = candidate_unit;  % Set the periodic unit
                num_repeats = n/p;  % Calculate number of repeating units
                return;  % Exit the function
            end
        end
    end
end